# Generated by Django 5.0.7 on 2024-07-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='patient_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
