# Generated by Django 5.0.7 on 2024-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('patients', '0002_customuser_patient_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patient_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[('Therapist', 'Терапевт'), ('Surgeon', 'Хирург'), ('Pediatrician', 'Педиатр')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит этот пользователь.', related_name='customuser_set', to='auth.group', verbose_name='группы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Doctor', 'Доктор'), ('Nurse', 'Медсестра'), ('Admin', 'Администратор')], default='Doctor', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Специфичные разрешения для этого пользователя.', related_name='customuser_set', to='auth.permission', verbose_name='разрешения пользователя'),
        ),
    ]
