# Generated by Django 5.0.7 on 2024-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_date_of_birth_alter_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Doctor', 'Доктор'), ('Nurse', 'Медсестра'), ('Admin', 'Администратор')], max_length=50),
        ),
    ]
